export { LEGACY_AGENT_MAPPING as AGENT_NAME_MAP, BUILTIN_AGENT_NAMES, migrateAgentName, migrateConfigKeys as migrateAgentNames } from "./migration/agent-names"
export { HOOK_NAME_MAP, migrateHookNames } from "./migration/hook-names"
export { MODEL_VERSION_MAP, migrateModelVersions } from "./migration/model-versions"
export { MODEL_TO_CATEGORY_MAP, migrateAgentConfigToCategory, shouldDeleteAgentConfig } from "./migration/agent-category"
export { migrateConfigFile } from "./migration/config-migration"